export const environment = {
    production: false,
    API_ENDPOINT: 'http://localhost:3000/api/',
    AUTH_TOKEN_KEY: "access_token",
    STATUS_OK: 200,
    MSG_LOGIN_FAIL: "Login faild.",
    MSG_REGISTER_FAIL: "Register faild.",
    MSG_CREATED: "Created Successfully",
    MSG_CREATE_FAILD: "Create failed.",
    MSG_ACTOR_INSERT_FAIL: "Cast add failed",
    MSG_ACTOR_INSERT_SUCCESS: "Cast added",
    MSG_ACTOR_UPDATE_FAIL: "Cast update failed",
    MSG_UPDATE_SUCCESS: "Update successfully.",
    MSG_UPDATE_FAILD: "Update faild.",
    MSG_ACTOR_UPDATE_SUCCESS: "Cast updated",
    MSG_DELETE_FAIL: "Delete failed",
    MSG_DELETE_SUCCESS: "Delete success",
    MSG_MOVIE_INSERT_FAIL: "Movie add failed",
    MSG_MOVIE_INSERT_SUCCESS: "Movie added",
    MSG_MOVIE_UPDATE_FAIL: "Movie update failed",
    MSG_MOVIE_UPDATE_SUCCESS: "Movie updated",
    MSG_ADDED_SCCESSFULLY: " added successfully.",
    TITLE_ADD: "Add",
    TITLE_UPDATE: "Update",
};
